#!/bin/sh
NEKOPATH=/usr/neko/lib:/usr/bin:./bin ./bin/hxttpd-bin --docroot=./html --pluginpath=./bin --port=8080 --load=ModHive --debug=5
#NEKOPATH=/usr/neko/lib:/usr/bin:./bin ./bin/hxttpd-bin --docroot=./html --pluginpath=./bin --port=8080 --load=ModNeko --debug=5
