ifeq ($(ARCH),linux)
  export BUILD=BUILD_LINUX
  export ARCH=linux
  export ARCH_CAP=Linux
  export CC=i686-pc-linux-gnu-gcc
  export EXE=
  export NEKO=neko
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
endif
ifeq ($(ARCH),windows)
  export BUILD=BUILD_WINDOWS
  export ARCH=windows
  export ARCH_CAP=Windows
  export CC=i686-mingw32-gcc
  export EXE=.exe
  export NEKO=neko
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
endif
ifeq ($(ARCH),mac)
  export BUILD=BUILD_MAC
  export ARCH=mac
  export ARCH_CAP=Mac
  export CC=gcc
  export EXE=
  export NEKO=neko
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
endif
ifeq ($(ARCH),bsd)
  export BUILD=BUILD_BSD
  export ARCH=bsd
  export ARCH_CAP=Bsd
  export CC=gcc
  export EXE=
  export NEKO=neko
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib -L/usr/local/lib
  export INCPATH=-I ./ -I /usr/include/neko -I /usr/local/include/neko
  export LIBS=-lneko
endif

# What follows are cross compiler targets

ifeq ($(ARCH),wine)
  export BUILD=BUILD_WINDOWS
  override ARCH:=windows
  export ARCH=windows
  export ARCH_CAP=Windows
  export CC=i686-mingw32-gcc
  export EXE=.exe
  export NEKO=wine neko
  export NEKOTOOLS=wine nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
endif
ifeq ($(ARCH),xbsd)
  export BUILD=BUILD_WINDOWS
  override ARCH:=bsd
  export ARCH=bsd
  export ARCH_CAP=Bsd
  export CC=i686-freebsd-gcc
  export EXE=
  export NEKO=neko
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
endif

