ifeq ($(ARCH),linux)
  export BUILD=BUILD_LINUX
  export ARCH=linux
  export ARCH_CAP=Linux
  export CC=i686-pc-linux-gnu-gcc
  export EXE=
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
  export NEKOLIB=/usr/neko/lib
  export BINPATH=/usr/bin
  export SHARE=/usr/share/hxttpd
  export DOCROOT=/var/www/localhost/htdocs
endif
ifeq ($(ARCH),windows)
  export BUILD=BUILD_WINDOWS
  export ARCH=windows
  export ARCH_CAP=Windows
  export CC=i686-mingw32-gcc
  export EXE=.exe
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
  export NEKOLIB=c:\\neko
  export BINPATH=c:\\
  export SHARE=c:\\
  export DOCROOT=
endif
ifeq ($(ARCH),mac)
  export BUILD=BUILD_MAC
  export ARCH=mac
  export ARCH_CAP=Mac
  export CC=gcc
  export EXE=
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
  export NEKOLIB=/usr/neko/lib
  export BINPATH=/usr/bin
  export SHARE=/usr/share/hxttpd
  export DOCROOT=/var/www/localhost/htdocs
endif
ifeq ($(ARCH),bsd)
  export BUILD=BUILD_BSD
  export ARCH=bsd
  export ARCH_CAP=Bsd
  export CC=gcc
  export EXE=
  export NEKOTOOLS=nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
  export NEKOLIB=/usr/neko/lib
  export BINPATH=/usr/bin
  export SHARE=/usr/share/hxttpd
  export DOCROOT=/var/www/localhost/htdocs
endif
ifeq ($(ARCH),wine)
  export BUILD=BUILD_WINDOWS
  override ARCH:=windows
  export ARCH=windows
  export ARCH_CAP=Windows
  export CC=i686-mingw32-gcc
  export EXE=.exe
  export NEKOTOOLS=wine nekotools
  export LIBPATH=-L/usr/lib
  export INCPATH=-I ./ -I /usr/include/neko
  export LIBS=-lneko
  export NEKOLIB=~/.wine/drive_c/neko
  export BINPATH=~/.wine/drive_c/hxttpd
  export SHARE=~/.wine/drive_c/hxttpd
  export DOCROOT=/var/www/localhost/htdocs
endif


